export const COUNTRIES: Record<string, { name: string; flag: string; lat: number; lng: number }> = {
  US: { name: "United States", flag: "🇺🇸", lat: 38, lng: -97 },
  GB: { name: "United Kingdom", flag: "🇬🇧", lat: 54, lng: -2 },
  CA: { name: "Canada", flag: "🇨🇦", lat: 56, lng: -106 },
  AU: { name: "Australia", flag: "🇦🇺", lat: -25, lng: 134 },
  DE: { name: "Germany", flag: "🇩🇪", lat: 51, lng: 10 },
  FR: { name: "France", flag: "🇫🇷", lat: 46, lng: 2 },
  IN: { name: "India", flag: "🇮🇳", lat: 21, lng: 78 },
  JP: { name: "Japan", flag: "🇯🇵", lat: 36, lng: 138 },
  CN: { name: "China", flag: "🇨🇳", lat: 35, lng: 105 },
  BR: { name: "Brazil", flag: "🇧🇷", lat: -10, lng: -55 },
  RU: { name: "Russia", flag: "🇷🇺", lat: 61, lng: 105 },
  ID: { name: "Indonesia", flag: "🇮🇩", lat: -2, lng: 120 },
  MX: { name: "Mexico", flag: "🇲🇽", lat: 23, lng: -102 },
  IT: { name: "Italy", flag: "🇮🇹", lat: 42, lng: 12 },
  ES: { name: "Spain", flag: "🇪🇸", lat: 40, lng: -3 },
  NL: { name: "Netherlands", flag: "🇳🇱", lat: 52, lng: 5 },
  SA: { name: "Saudi Arabia", flag: "🇸🇦", lat: 24, lng: 45 },
  TR: { name: "Turkey", flag: "🇹🇷", lat: 39, lng: 35 },
  CH: { name: "Switzerland", flag: "🇨🇭", lat: 47, lng: 8 },
  SE: { name: "Sweden", flag: "🇸🇪", lat: 62, lng: 15 },
  PL: { name: "Poland", flag: "🇵🇱", lat: 52, lng: 19 },
  BE: { name: "Belgium", flag: "🇧🇪", lat: 50, lng: 4 },
  AR: { name: "Argentina", flag: "🇦🇷", lat: -34, lng: -64 },
  NG: { name: "Nigeria", flag: "🇳🇬", lat: 9, lng: 8 },
  ZA: { name: "South Africa", flag: "🇿🇦", lat: -29, lng: 24 },
  EG: { name: "Egypt", flag: "🇪🇬", lat: 26, lng: 30 },
  TH: { name: "Thailand", flag: "🇹🇭", lat: 15, lng: 100 },
  VN: { name: "Vietnam", flag: "🇻🇳", lat: 14, lng: 108 },
  KR: { name: "South Korea", flag: "🇰🇷", lat: 36, lng: 128 },
  MY: { name: "Malaysia", flag: "🇲🇾", lat: 4, lng: 113 },
  PH: { name: "Philippines", flag: "🇵🇭", lat: 11, lng: 122 },
  SG: { name: "Singapore", flag: "🇸🇬", lat: 1, lng: 103 },
  PK: { name: "Pakistan", flag: "🇵🇰", lat: 30, lng: 70 },
  BD: { name: "Bangladesh", flag: "🇧🇩", lat: 24, lng: 90 },
  AE: { name: "United Arab Emirates", flag: "🇦🇪", lat: 24, lng: 54 },
  IL: { name: "Israel", flag: "🇮🇱", lat: 31, lng: 34 },
  UA: { name: "Ukraine", flag: "🇺🇦", lat: 49, lng: 32 },
  IR: { name: "Iran", flag: "🇮🇷", lat: 32, lng: 53 },
  TW: { name: "Taiwan", flag: "🇹🇼", lat: 24, lng: 121 },
  CL: { name: "Chile", flag: "🇨🇱", lat: -30, lng: -71 },
  CO: { name: "Colombia", flag: "🇨🇴", lat: 1, lng: -74 },
  PE: { name: "Peru", flag: "🇵🇪", lat: -10, lng: -76 },
  QA: { name: "Qatar", flag: "🇶🇦", lat: 25, lng: 51 },
  KW: { name: "Kuwait", flag: "🇰🇼", lat: 29, lng: 48 },
  OM: { name: "Oman", flag: "🇴🇲", lat: 20, lng: 57 },
  BH: { name: "Bahrain", flag: "🇧🇭", lat: 26, lng: 50 },
  JO: { name: "Jordan", flag: "🇯🇴", lat: 31, lng: 36 },
  LB: { name: "Lebanon", flag: "🇱🇧", lat: 34, lng: 36 },
  SK: { name: "Slovakia", flag: "🇸🇰", lat: 49, lng: 19 },
  CZ: { name: "Czech Republic", flag: "🇨🇿", lat: 50, lng: 15 },
  HU: { name: "Hungary", flag: "🇭🇺", lat: 47, lng: 19 },
  AT: { name: "Austria", flag: "🇦🇹", lat: 48, lng: 14 },
  DK: { name: "Denmark", flag: "🇩🇰", lat: 56, lng: 10 },
  NO: { name: "Norway", flag: "🇳🇴", lat: 60, lng: 9 },
  FI: { name: "Finland", flag: "🇫🇮", lat: 62, lng: 26 },
  IE: { name: "Ireland", flag: "🇮🇪", lat: 53, lng: -8 },
  PT: { name: "Portugal", flag: "🇵🇹", lat: 39, lng: -8 },
  GR: { name: "Greece", flag: "🇬🇷", lat: 39, lng: 22 },
  NZ: { name: "New Zealand", flag: "🇳🇿", lat: -40, lng: 174 },
  MA: { name: "Morocco", flag: "🇲🇦", lat: 31, lng: -7 },
  KE: { name: "Kenya", flag: "🇰🇪", lat: 0, lng: 38 },
  GH: { name: "Ghana", flag: "🇬🇭", lat: 8, lng: -2 },
  ET: { name: "Ethiopia", flag: "🇪🇹", lat: 9, lng: 40 },
  RO: { name: "Romania", flag: "🇷🇴", lat: 46, lng: 25 },
  KZ: { name: "Kazakhstan", flag: "🇰🇿", lat: 48, lng: 68 },
}
